package com.wakefern.logging;

/*
 *  author: Danny zheng
 *  date:   7/23/2018
 *  
 *  all error type are for the high-level REST end points
 */
public enum ErrorType {
	
	APIM_FORGOT_FSN_EMAIL,

	NEW_RELIC_DEPLOYMENT,

	
	JWT_TOKEN_GET_TOKEN,

	PUSH2DEVICE_REGISTER,
	PUSH2DEVICE_UNREGISTER,
	
	WALLET_GET_WALLET,

	
	/*
	 * 
	 * Date:    2021-09-01
	 * Purpose: Below are for the new Wakefern/3rd party integration APIs Proxy to support the new V8 mobile app
	 * 
	 */
	
	PROXY_APIM_SRFH_GET_UPCOMING_ORDERS,
	PROXY_APIM_SRFH_CREATE_CURBSIDE_SESSION,
	PROXY_APIM_SRFH_GET_CURBSIDE_SESSION,
	PROXY_APIM_SRFH_UPDATE_CURBSIDE_SESSION,
	PROXY_APIM_SMS_ENROLLMENTS,
	
	PROXY_PRODX_GET_PRODUCT_COMPLEMENTS,
	
	PROXY_COUPONS_V3_GET_USER_SESSION,
	PROXY_COUPONS_V3_GET_COUPON_LIST,
	PROXY_COUPONS_V3_GET_AVAILABLE_COUPONS,
	PROXY_COUPONS_V3_GET_EXPIRED_COUPONS,
	PROXY_COUPONS_V3_GET_CLIPPED_COUPONS,
	PROXY_COUPONS_V3_GET_REDEEMED_COUPONS,
	PROXY_COUPONS_V3_GET_COUPON_FROM_PROMOCODE,
	PROXY_COUPONS_V3_ADD_COUPON_TO_PPC,
	PROXY_COUPONS_V3_REMOVE_COUPON_FROM_PPC,
	PROXY_COUPONS_V3_GET_COUPON_BY_UPC,
	PROXY_COUPONS_V3_GET_UPC_LIST_BY_COUPON_ID,
	PROXY_COUPONS_V3_GET_COUPONS_BY_EXTERNAL_COUPON_IDS,
	PROXY_COUPONS_V3_GET_COUPONS_BY_STORE_ID,
	PROXY_COUPONS_V3_GET_SOCIAL_OFFERS_BY_QUERY,
	
	PROXY_DIGITAL_RECEIPT_GET_DETAIL,
	PROXY_DIGITAL_RECEIPT_GET_SUMMARY,
	
	PROXY_NUTRITION_GET_NUTRITION,
	
	PROXY_RECIPES_LOCAI_RECIPE_TAGS,
	PROXY_RECIPES_LOCAI_LOOKUP_RECIPES,
	PROXY_RECIPES_LOCAI_SEARCH_RECIPES,
	PROXY_RECIPES_LOCAI_COMPLETE_RECIPES,
	PROXY_RECIPES_LOCAI_PRODUCT_LOOKUP,
	PROXY_RECIPES_LOCAI_PRODUCT_DETAILS,
	PROXY_RECIPES_LOCAI_GET_USER_INFO,
	PROXY_RECIPES_LOCAI_GET_USER_PROFILE,
	PROXY_RECIPES_LOCAI_SET_USER_PROFILE,
	PROXY_RECIPES_LOCAI_GET_USER_FAVORITES,
	PROXY_RECIPES_LOCAI_SAVE_DISH_FAVORITE,
	PROXY_RECIPES_LOCAI_GET_RECIPE_CATEGORIES,
	PROXY_RECIPES_LOCAI_HOMEPAGE_CONFIG,
	PROXY_RECIPES_LOCAI_RECIPE_TRACKING,
	PROXY_RECIPES_LOCAI_PRODUCT_SEARCHANDIZING,
	PROXY_RECIPES_LOCAI_SEARCH_BY_SKUS,
	PROXY_RECIPES_LOCAI_GET_SHELVES,
	PROXY_RECIPES_LOCAI_PRODUCT_LOOKUP_BY_SKUS,
	
	PROXY_REWARDS_GET_POINTS_FOR_PPC,
	
	PROXY_PPCJWTTOKEN_GET_PPC_JWT_TOKEN,
	
	PROXY_MI9V8_GET_PLANNING_LIST_ITEM_LOCATOR,
	PROXY_ITEMLOCATOR_GET_ITEM_LOCATOR,
	PROXY_ITEMLOCATOR_GET_CART_ITEM_LOCATOR;
}
