---
COUPON_V2_TOKEN: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODM1NjgzODAsImVtYWlsIjoiS0VWSU4uSkFOR0BXQUtFRkVSTi5DT00iLCJmdWxsTmFtZSI6ImNvdXBvbldlYlVzZXJzIiwiaWF0IjoxNTI1ODg4MzgwfQ.Numfi4df5nSvfR9Rt2POzA4Fki-iw7CAQT6rmjb32IY
SR_MWG_STG_TOKEN: 13B4312E-D431-4C53-A16C-5998B2F53482
SR_MWG_PRD_TOKEN: b5e4d368-d5ee-47ce-9c7d-423de1c879e6
TFG_MWG_PRD_TOKEN: 62081B21-0885-4544-8849-326195C8F9CD
ITEM_LOC_TOKEN: eyJleHAiOjE0NzYxMDQyMTM1NDYsInN1YiI6InNmamMxcGFzc3dkIiwiaXNzIjoiaHR0cDovL3dha2VmZXJuLmNvbSJ9
PROD_NOT_FND_LOGIN: ZzntD70b0dKNjRrfTOmb4FP08bd9fWsX:ZDn7RrcRhN+ByAnDCPTU
SR_PROD_REC_TOKEN: e9d69feb-012b-45e1-bf10-eea13424495d
TFG_PROD_REC_TOKEN: 17a7139d-7268-4548-a441-29dbb380a592