---
SRMOBILE_CORS: true
SRMOBILE_CHAIN: ShopRiteStage
COUPON_SERVICE: Staging
SRMOBILE_PAPERTRAIL: srmobilelog-dev

API_HIGH_TIMEOUT: 40000
API_MEDIUM_TIMEOUT: 15000
API_LOW_TIMEOUT: 5000
HTTP_DEFAULT_CONNECT_TIMEOUT_MS: 5000
HTTP_DEFAULT_READ_TIMEOUT_MS: 40000
RECIPE_SERVICE: Staging
WALLET_SERVICE: Staging
CITRUS_SERVICE: Staging