---
SRMOBILE_CORS: true
SRMOBILE_CHAIN: ShopRiteStage
COUPON_SERVICE: Staging
SRMOBILE_PAPERTRAIL: srmobilelog-dev

API_HIGH_TIMEOUT: 40000
API_MEDIUM_TIMEOUT: 15000
API_LOW_TIMEOUT: 5000
HTTP_DEFAULT_CONNECT_TIMEOUT_MS: 5000
HTTP_DEFAULT_READ_TIMEOUT_MS: 30000
RECIPE_SHELF_THREAD_POOL_SIZE: 100

RECIPE_SERVICE: Staging
WALLET_SERVICE: Staging
SRFH_ORDERS_SERVICE: Staging
SRFH_CURBSIDE_SERVICE: Staging
PRODX_SERVICE: Staging
MI9V8_SERVICE: Staging

REWARD_POINT_SERVICE: Staging