---
COUPON_SERVICE: Production
SRMOBILE_PAPERTRAIL: srapplog-prod

API_HIGH_TIMEOUT: 30000
API_MEDIUM_TIMEOUT: 10000
API_LOW_TIMEOUT: 3000
HTTP_DEFAULT_CONNECT_TIMEOUT_MS: 5000
HTTP_DEFAULT_READ_TIMEOUT_MS: 30000
RECIPE_SHELF_THREAD_POOL_SIZE: 100

RECIPE_SERVICE: Production
WALLET_SERVICE: Production
SRFH_ORDERS_SERVICE: Production
SRFH_CURBSIDE_SERVICE: Production
PRODX_SERVICE: Production
MI9V8_SERVICE: Production
PUSH2DEVICE_SERVICE: Production
PUSH2DEVICE_STG_URL: https://srpushservicedev.azurewebsites.net
PUSH2DEVICE_PROD_URL: https://srprodpushservice.azurewebsites.net

REWARD_POINT_SERVICE: Production

MUTE_ERROR_LOG: true
MUTE_HTTP_CODE: 401,409

ITEM_LOCATOR_PARTITION_SIZE: 50
ITEM_LOCATOR_CACHE_ENABLED: true