---
SRMOBILE_CORS: false
SRMOBILE_CHAIN: ShopRiteProd
COUPON_SERVICE: Production
SRMOBILE_PAPERTRAIL: srapplog-prod
SRMOBILE_NEWRELIC: srnewrelic

API_HIGH_TIMEOUT: 30000
API_MEDIUM_TIMEOUT: 10000
API_LOW_TIMEOUT: 3000
HTTP_DEFAULT_CONNECT_TIMEOUT_MS: 5000
HTTP_DEFAULT_READ_TIMEOUT_MS: 30000
RECIPE_SERVICE: Production
WALLET_SERVICE: Production
CITRUS_SERVICE: Production # TODO