---
SRMOBILE_CORS: true
SRMOBILE_CHAIN: ShopRiteProd
COUPON_SERVICE: Production
SRMOBILE_PAPERTRAIL: srmobilelog-dev
ENABLE_CART_ITEM_LOCATOR: true
API_HIGH_TIMEOUT: 30000
API_MEDIUM_TIMEOUT: 10000
API_LOW_TIMEOUT: 3000