---
SRMOBILE_CORS: true
SRMOBILE_CHAIN: ShopRiteProd
COUPON_SERVICE: Production
SRMOBILE_PAPERTRAIL: srmobilelog-dev

API_HIGH_TIMEOUT: 30000
API_MEDIUM_TIMEOUT: 10000
API_LOW_TIMEOUT: 3000
HTTP_DEFAULT_CONNECT_TIMEOUT_MS: 5000
HTTP_DEFAULT_READ_TIMEOUT_MS: 30000
RECIPE_SHELF_THREAD_POOL_SIZE: 100

PUSH2DEVICE_SERVICE: Production

# RECIPE_SERVICE & SRMOBILE_CHAIN must be consistent since some Locai's back-end APIs access Mi9's API server
RECIPE_SERVICE: Production
WALLET_SERVICE: Production
SRFH_ORDERS_SERVICE: Production
SRFH_CURBSIDE_SERVICE: Production
PRODX_SERVICE: Production
MI9V8_SERVICE: Production

REWARD_POINT_SERVICE: Production